# Generated by Django 3.2.7 on 2022-01-23 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airportdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AirportCode', models.CharField(max_length=3)),
                ('ICAO', models.CharField(max_length=4)),
                ('CountryCode', models.EmailField(max_length=2)),
                ('DO', models.IntegerField()),
                ('cn', models.CharField(max_length=43)),
                ('label', models.CharField(max_length=150)),
                ('ContName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'airportdata',
            },
        ),
        migrations.CreateModel(
            name='Newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('uemail', models.EmailField(max_length=100)),
                ('umobile', models.CharField(max_length=100)),
                ('upassword', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'hdf_user',
            },
        ),
        migrations.CreateModel(
            name='TempData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TraceId', models.CharField(max_length=200)),
                ('json_data', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'temp_data',
            },
        ),
    ]
